FROM alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
	apk --no-cache add ca-certificates

WORKDIR /root/

COPY drone-oss-cache /

CMD ["/drone-oss-cache"]